# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
import numpy as np

arr = np.arange(6)
print(arr)
print(arr.dtype)


[0 1 2 3 4 5]
int64


# 2.  Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7]

In [ ]:
arr = np.array([1.5, 2.6, 3.7])

is_float64 = arr.dtype == np.float64
print(is_float64)


True


# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)
print(arr.dtype)


[1.+2.j 3.+4.j 5.+6.j]
complex128


# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
arr = np.arange(6)
print(arr)
print(arr.dtype)


[0 1 2 3 4 5]
int64


In [ ]:
arr = arr.astype(np.float32)
print(arr)
print(arr.dtype)


[0. 1. 2. 3. 4. 5.]
float32


# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
arr = np.array([1.123456789, 2.987654321, 3.456789123], dtype=np.float64)
print(arr)
print(arr.dtype)

[1.12345679 2.98765432 3.45678912]
float64


In [ ]:
arr = arr.astype(np.float32)
print(arr)
print(arr.dtype)

[1.1234568 2.9876542 3.456789 ]
float32


# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.

In [ ]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([1, 2, 3, 4])
shape, size, dtype = array_attributes(arr)
print(f"Shape: {shape}")
print(f"Size: {size}")
print(f"Data Type: {dtype}")



Shape: (4,)
Size: 4
Data Type: int64


# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)
print(f"Dimensionality: {dimension}")


Dimensionality: 2


# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [ ]:
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

arr = np.array([1, 2, 3, 4], dtype=np.int32)
item_size, total_size = item_size_info(arr)
print(f"Item Size: {item_size} bytes")
print(f"Total Size: {total_size} bytes")


Item Size: 4 bytes
Total Size: 16 bytes


# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array

In [ ]:
def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)  # The strides  gives the number of bytes to step in each dimension when traversing an array.
print(f"Strides: {strides}")


Strides: (24, 8)


# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [ ]:
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print(f"Shape: {shape}")
print(f"Strides: {strides}")

Shape: (2, 3)
Strides: (24, 8)


# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [ ]:
def create_zeros_array(n):
    return np.zeros(n)

arr = create_zeros_array(5)
print(arr)



[0. 0. 0. 0. 0.]


# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [ ]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

matrix = create_ones_matrix(3, 4)
print(matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [ ]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

arr = generate_range_array(1, 10, 2)
print(arr)


[1 3 5 7 9]


# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

In [ ]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

arr = generate_linear_space(0.0, 1.0, 5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]


# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

In [ ]:
def create_identity_matrix(n):
    return np.eye(n)

identity_matrix = create_identity_matrix(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 16. Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
def list_to_array(my_list):
    return np.array(my_list)

my_list = [1, 2, 3, 4, 5]
array = list_to_array(my_list)
print(array)


[1 2 3 4 5]


# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.


In [ ]:
# Create a NumPy array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# create a new array object with the same data using view
view_array = original_array.view()

# Modify the original array
original_array[0, 0] = 10

print("Original Array:")
print(original_array)

print("\nView Array:")
print(view_array)


Original Array:
[[10  2  3]
 [ 4  5  6]]

View Array:
[[10  2  3]
 [ 4  5  6]]


# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)


arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along axis 0 (vertically)
result_axis0 = concatenate_arrays(arr1, arr2, axis=0) # The number of columns must be the same for all arrays along this axis.
print("Concatenated along axis 0:")
print(result_axis0)

# Concatenate along axis 1 (horizontally)             # The number of rows must be the same for all arrays along this axis.
result_axis1 = concatenate_arrays(arr1, arr2, axis=1)
print("\nConcatenated along axis 1:")
print(result_axis1)


Concatenated along axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenated along axis 1:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# 19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [ ]:
# Create two NumPy arrays with different shapes but the same number of rows
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6, 7], [8, 9, 10]])

# Concatenate them horizontally (axis=1)
result = np.concatenate((arr1, arr2), axis=1)

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nConcatenated Result:")
print(result)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[ 5  6  7]
 [ 8  9 10]]

Concatenated Result:
[[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
def vertical_stack(arrays):
    return np.vstack(arrays)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
arr3 = np.array([[7, 8], [9, 10]])

# Stack them vertically
result = vertical_stack([arr1, arr2, arr3])

print("Vertically Stacked Result:")
print(result)



Vertically Stacked Result:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size

In [ ]:
def range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

start = 1
stop = 10
step = 2

result = range_array(start, stop, step)
print(result)


[1 3 5 7 9]


# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [ ]:
def equally_spaced_array(start=0, stop=1, num=10):
    return np.linspace(start, stop, num)

result = equally_spaced_array()
print(result)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive)

In [ ]:
def logarithmically_spaced_array(start=1, stop=1000, num=5):
    return np.logspace(np.log10(start), np.log10(stop), num)

result = logarithmically_spaced_array()
print(result)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [ ]:
import numpy as np
import pandas as pd

# Generate a NumPy array with random integers between 1 and 100
data = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

print(df)


   Column1  Column2  Column3
0       53       40       89
1       10       76       99
2       30       61       13
3        6       66       51
4       44       31       99


# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
def replace_negative_with_zero(df, column_name):

    # Use NumPy's where function to replace negative values with 0
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Create a sample DataFrame
df = pd.DataFrame({
    'A': [10, -20, 30, -40, 50],
    'B': [-5, 15, -25, 35, -45]
})

# Replace negative values in column 'A' with zeros
df = replace_negative_with_zero(df, 'A')

print(df)


    A   B
0  10  -5
1   0  15
2  30 -25
3   0  35
4  50 -45


# 26. Access the 3rd element from the given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element
third_element = arr[2]

print(third_element)


30


# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

 arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]

In [ ]:
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]

print(element)


6


# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
 arr = np.array([3, 8, 2, 10, 5, 7])

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])

# Create a boolean mask
mask = arr > 5

# Use the mask to extract the elements
filtered_elements = arr[mask]

print(filtered_elements)


[ 8 10  7]


# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_array = arr[2:6]

print(sliced_array)


[3 4 5 6]


# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
 arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])


In [ ]:
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

sub_array = arr_2d[0:2, 1:3]

print(sub_array)


[[2 3]
 [5 6]]


# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [ ]:
def extract_elements(arr_2d, indices):
   rows, cols = indices[:, 0], indices[:, 1]
   return arr_2d[rows, cols]


# Given 2D NumPy array
arr_2d = np.array([[10, 20, 30],
                    [40, 50, 60],
                    [70, 80, 90]])

# Indices for extraction (row_index, column_index)
indices = np.array([[0, 1],
                    [1, 2],
                    [2, 0]])
# Extract elements based on the indices
extracted_elements = extract_elements(arr_2d, indices)

print(extracted_elements)

[20 60 70]


# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing

In [ ]:
def filter_gt(arr, threshold):

  # Create a boolean mask for elements greater than the threshold
    mask = arr > threshold

    # Use the mask to filter elements
    return arr[mask]

# Given 1D NumPy array
arr = np.array([1, 5, 8, 12, 3, 7])

# Define the threshold
threshold = 6

# Filter elements greater than the threshold
filtered_elements = filter_gt(arr, threshold)

print(filtered_elements)

[ 8 12  7]


# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [ ]:
def extract_3d_elements(arr_3d, row_indices, col_indices, depth_indices):
   # Extract elements based on the provided indices
    return arr_3d[row_indices, col_indices, depth_indices]

# Given 3D NumPy array
arr_3d = np.array([[[10, 20, 30],
                    [40, 50, 60]],
                   [[70, 80, 90],
                    [100, 110, 120]],
                   [[130, 140, 150],
                    [160, 170, 180]]])

# Indices for extraction
row_indices = np.array([0, 1, 2])  # Rows
col_indices = np.array([1, 0, 1])  # Columns
depth_indices = np.array([2, 1, 0])  # Depths

# Extract elements based on the indices
extracted_elements = extract_3d_elements(arr_3d, row_indices, col_indices, depth_indices)

print(extracted_elements)

[ 60  80 160]


# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [ ]:
def filter_elements(arr, condition1, condition2):
    return arr[condition1 & condition2]

# Example usage:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition1 = arr > 3
condition2 = arr % 2 == 0

filtered_elements = filter_elements(arr, condition1, condition2)
print(filtered_elements)


[ 4  6  8 10]


# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [ ]:
def extract_elements(matrix, row_indices, col_indices):
    return matrix[row_indices, col_indices]

# Example usage:
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

extracted_elements = extract_elements(matrix, row_indices, col_indices)
print(extracted_elements)

[20 60 70]


# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
# Define the array with shape (3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a scalar value of 5 to each element
result = arr + 5

print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [ ]:
# Define the arrays
arr1 = np.array([[1, 2, 3]])  # Shape (1, 3)
arr2 = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120]])  # Shape (3, 4)

result = arr2 * arr1.T # Converting rows to column for multiplication
print(result)

[[ 10  20  30  40]
 [100 120 140 160]
 [270 300 330 360]]


# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [ ]:
# Define the arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])  # Shape (4, 3)

arr1_reshaped = arr1[:, :arr2.shape[1]]  # Reshape arr1 to match the number of columns in arr2

# Add arr1 to each row of arr2
result = arr2 + arr1_reshaped

print(result)

[[ 11  22  33]
 [ 41  52  63]
 [ 71  82  93]
 [101 112 123]]


# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [ ]:
arr1 = np.array([[1],
                 [2],
                 [3]])  # Shape (3, 1)

arr2 = np.array([[4, 5, 6]])  # Shape (1, 3)

# Add the arrays using broadcasting
result = arr1 + arr2

print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [ ]:
# Define the arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)

arr2 = np.array([[10, 20],
                 [30, 40]])  # Shape (2, 2)

# Reshape arr2 to be broadcastable with arr1
# We will reshape arr2 to shape (2, 1, 2) and then multiply
arr2_reshaped = arr2[:, np.newaxis, :]  # Shape (2, 1, 2)

# Multiply arr1 by arr2_reshaped
# This will broadcast arr1 (2, 3) with arr2_reshaped (2, 1, 2)
result = arr1[:, :, np.newaxis] * arr2_reshaped  # Shape (2, 3, 2)

print(result)

[[[ 10  20]
  [ 20  40]
  [ 30  60]]

 [[120 160]
  [150 200]
  [180 240]]]


# 41. Calculate column-wise mean for the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate column-wise mean
column_mean = np.mean(arr, axis=0)

print(column_mean)

[2.5 3.5 4.5]


# 42. Find maximum value in each row of the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the maximum value in each row
row_max = np.max(arr, axis=1)

print(row_max)

[3 6]


# 43. For the given array, find indices of maximum value in each column.
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find indices of the maximum value in each column
indices_of_max = np.argmax(arr, axis=0)

print(indices_of_max)

[1 1 1]


# 44. For the given array, apply custom function to calculate moving sum along rows.
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
def moving_sum(arr, window_size):
    # Ensure the window size is valid
    if window_size > arr.shape[1]:
        raise ValueError("Window size must be less than or equal to the number of columns")

    # Initialize result array
    num_rows, num_cols = arr.shape
    result = np.zeros((num_rows, num_cols - window_size + 1))

    # Calculate moving sums for each row
    for i in range(num_rows):
        for j in range(num_cols - window_size + 1):
            result[i, j] = np.sum(arr[i, j:j + window_size])

    return result

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Specify window size
window_size = 2

# Calculate moving sum along rows
result = moving_sum(arr, window_size)

print(result)


[[ 3.  5.]
 [ 9. 11.]]


# 45. In the given array, check if all elements in each column are even.
 arr = np.array([[2, 4, 6], [3, 5, 7]])


In [ ]:
# Define the array
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if all elements in each column are even
all_even = np.all(arr % 2 == 0, axis=0)

print(all_even)


[False False False]


# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

 original_array = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
original_array = np.array([1, 2, 3, 4, 5, 6])

# Define the desired dimensions
m = 2  # Number of rows
n = 3  # Number of columns

# Reshape the array
reshaped_matrix = original_array.reshape(m, n)

print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


# 47. Create a function that takes a matrix as input and returns the flattened array.
 input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
def flatten_matrix(matrix):
    # Flatten the matrix into a 1D array
    return matrix.flatten()

# Define the input matrix
input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])

# Flatten the matrix
flattened_array = flatten_matrix(input_matrix)

print(flattened_array)


[1 2 3 4 5 6]


# 48. Write a function that concatenates two given arrays along a specified axis.

 array1 = np.array([[1, 2], [3, 4]])
 array2 = np.array([[5, 6], [7, 8]])

In [ ]:
def concat(a1, a2, ax=0):
    # Concatenate the two arrays along the specified axis
    return np.concatenate((a1, a2), axis=ax)

# Define the input arrays
a1 = np.array([[1, 2],
               [3, 4]])

a2 = np.array([[5, 6],
               [7, 8]])

# Concatenate the arrays along axis 0 (vertically)
result_ax0 = concat(a1, a2, ax=0)
print("Concatenated along axis 0:\n", result_ax0)

# Concatenate the arrays along axis 1 (horizontally)
result_ax1 = concat(a1, a2, ax=1)
print("Concatenated along axis 1:\n", result_ax1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
 original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
def split_arr(arr, n, ax=0):
    # Split the array into 'n' sub-arrays along the specified axis
    return np.split(arr, n, axis=ax)

# Define the original array
orig_arr = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Split the array into 3 sub-arrays along axis 0 (rows)
split_ax0 = split_arr(orig_arr, 3, ax=0)
print("Split along axis 0:")
for sub_arr in split_ax0:
    print(sub_arr)

# Split the array into 3 sub-arrays along axis 1 (columns)
split_ax1 = split_arr(orig_arr, 3, ax=1)
print("Split along axis 1:")
for sub_arr in split_ax1:
    print(sub_arr)

Split along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]
Split along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
 original_array = np.array([1, 2, 3, 4, 5])
 indices_to_insert = [2, 4]
 values_to_insert = [10, 11]
 indices_to_delete = [1, 3]

In [ ]:
import numpy as np

def modify_array(arr, indices_insert, values_insert, indices_delete):
    # Insert values into the array
    arr = np.insert(arr, indices_insert, values_insert)

    # Adjust indices for deletion
    # Since insertion has changed the array, the indices need to be recalculated
    # Sort indices to delete in reverse order to avoid shifting issues
    indices_delete = sorted(indices_delete, reverse=True)

    # Delete elements from the array
    for idx in indices_delete:
        arr = np.delete(arr, idx)

    return arr

# Define the original array
orig_arr = np.array([1, 2, 3, 4, 5])

# Define indices and values to insert
indices_to_insert = [2, 4]
values_to_insert = [10, 11]

# Define indices to delete
indices_to_delete = [1, 3]

# Modify the array
result_arr = modify_array(orig_arr, indices_to_insert, values_to_insert, indices_to_delete)

print("Modified array:\n", result_arr)


Modified array:
 [ 1 10  4 11  5]


# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [ ]:
# Create arr1 with random integers
shape = (3, 4)  # Example shape, you can choose any shape
arr1 = np.random.randint(0, 10, size=shape)

# Create arr2 with integers from 1 to 10, ensuring no values exceed 10
arr2 = np.random.randint(1, 11, size=shape)  # Random integers between 1 and 10

# Perform element-wise addition
result = arr1 + arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nElement-wise addition result:")
print(result)

arr1:
[[2 4 8 6]
 [4 3 4 5]
 [7 4 2 3]]

arr2:
[[10 10  8  8]
 [ 1  3 10  6]
 [ 2  2  5  6]]

Element-wise addition result:
[[12 14 16 14]
 [ 5  6 14 11]
 [ 9  6  7  9]]


# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [ ]:
# Generate arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1).reshape(2, 5)  # Example shape (2, 5) to fit the range 10 to 1

# Generate arr2 with integers from 1 to 10
arr2 = np.arange(1, 11).reshape(2, 5)  # Example shape (2, 5) to match arr1's shape

# Perform element-wise subtraction
result = arr1 - arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nElement-wise subtraction result:")
print(result)

arr1:
[[10  9  8  7  6]
 [ 5  4  3  2  1]]

arr2:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Element-wise subtraction result:
[[ 9  7  5  3  1]
 [-1 -3 -5 -7 -9]]


# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`

In [ ]:
# Generate arr1 with random integers
shape = (3, 4)  # Example shape
arr1 = np.random.randint(1, 10, size=shape)  # Random integers between 1 and 9

# Generate arr2 with integers from 1 to 5, reshaped to match arr1's shape
# Adjust size of arr2 to match arr1's shape
arr2 = np.random.randint(1, 6, size=shape)  # Random integers between 1 and 5

# Perform element-wise multiplication
result = arr1 * arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nElement-wise multiplication result:")
print(result)

arr1:
[[8 7 3 9]
 [8 6 9 6]
 [7 8 8 7]]

arr2:
[[5 3 4 5]
 [5 3 3 1]
 [2 3 4 5]]

Element-wise multiplication result:
[[40 21 12 45]
 [40 18 27  6]
 [14 24 32 35]]


# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [ ]:
 # Generate arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2).reshape(1, 5)  # Reshape to (1, 5) for broadcasting

# Generate arr2 with integers from 1 to 5
arr2 = np.arange(1, 6).reshape(1, 5)  # Reshape to (1, 5) to match arr1's shape

# Perform element-wise division
result = arr1 / arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nElement-wise division result:")
print(result)

arr1:
[[ 2  4  6  8 10]]

arr2:
[[1 2 3 4 5]]

Element-wise division result:
[[2. 2. 2. 2. 2.]]


# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise

In [ ]:
# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create arr2 with the same numbers reversed
arr2 = arr1[::-1]  # Reverse the array

# Calculate the exponentiation of arr1 raised to the power of arr2 element-wise
result = np.power(arr1, arr2)

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nExponentiation result (arr1 ^ arr2):")
print(result)

arr1:
[1 2 3 4 5]

arr2:
[5 4 3 2 1]

Exponentiation result (arr1 ^ arr2):
[ 1 16 27 16  5]


# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
 arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [ ]:
def count_substring_occurrences(arr, substring):
  # Convert the array to a list of strings if it's not already
    arr = arr.astype(str)

    # Use numpy's vectorized string operations to find the substring
    occurrences = np.char.find(arr, substring) != -1

    # Count the number of True values in the boolean array
    count = np.sum(occurrences)

    return count

# Example usage
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
count = count_substring_occurrences(arr, substring)

print(f"Occurrences of '{substring}':", count)

Occurrences of 'hello': 3


# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
 arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
def extract_uppercase(arr):
      # Convert array to string type (in case it's not already)
    arr = arr.astype(str)

    # Extract uppercase characters from each string
    def get_uppercase(s):
        return ''.join(char for char in s if char.isupper())

    # Apply the function to each element in the array
    result = np.array([get_uppercase(s) for s in arr])

    return result

# Example usage
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase(arr)

print("Original array:")
print(arr)
print("\nArray with uppercase characters extracted:")
print(result)


Original array:
['Hello' 'World' 'OpenAI' 'GPT']

Array with uppercase characters extracted:
['H' 'W' 'OAI' 'GPT']


# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [2]:
import numpy as np
def replace_substring(arr, old_substring, new_substring):
   # Convert array to string type (in case it's not already)
    arr = arr.astype(str)

    # Replace old substring with new substring
    replaced = np.char.replace(arr, old_substring, new_substring)

    return replaced

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'
result = replace_substring(arr, old_substring, new_substring)

print("Original array:")
print(arr)
print("\nArray after replacement:")
print(result)

Original array:
['apple' 'banana' 'grape' 'pineapple']

Array after replacement:
['orange' 'banana' 'grape' 'pineorange']


# 59. Write a function that concatenates strings in a NumPy array element-wise.
 arr1 = np.array(['Hello', 'World'])

 arr2 = np.array(['Open', 'AI'])

In [3]:
def concatenate_strings(arr1, arr2):
   # Convert arrays to string type (in case they're not already)
    arr1 = arr1.astype(str)
    arr2 = arr2.astype(str)

    # Concatenate corresponding elements from both arrays
    concatenated = np.char.add(arr1, arr2)

    return concatenated

# Example usage
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = concatenate_strings(arr1, arr2)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nArray after concatenation:")
print(result)

Array 1:
['Hello' 'World']

Array 2:
['Open' 'AI']

Array after concatenation:
['HelloOpen' 'WorldAI']


# 60. Write a function that finds the length of the longest string in a NumPy array.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [4]:
def longest_string_length(arr):
  # Convert array to string type (in case it's not already)
    arr = arr.astype(str)

    # Find the length of each string
    lengths = np.char.str_len(arr)

    # Find the maximum length
    max_length = np.max(lengths)

    return max_length

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = longest_string_length(arr)

print("Array:")
print(arr)
print("\nLength of the longest string:")
print(result)

Array:
['apple' 'banana' 'grape' 'pineapple']

Length of the longest string:
9


# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions

In [5]:
# Generate a dataset of 100 random integers between 1 and 1000
data = np.random.randint(1, 1001, size=100)

# Compute statistics
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

# Print results
print("Dataset:")
print(data)
print("\nMean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Dataset:
[717 682 343  20 531  81 368 362 571 289 575 613 351 209 112 912 521 770
 562 406 594 988  74 105 555 284 800 747 173 128 312 192  32  41 592  24
 290 541 701 973  30 606 851 544 512 636 838 540 679 409 739 600 650 544
 679 312 835 710  25 652 820 803 447 441 379 861 569 379 479 652 686 516
 137 805 874 747 426 357 331 452 345 994 196 996 914 880 282 526 986 621
 938 724 929 676 880 338  31 748 450 655]

Mean: 528.02
Median: 549.5
Variance: 73450.35960000003
Standard Deviation: 271.01726808452634


# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [6]:
# Generate an array of 50 random numbers between 1 and 100
data = np.random.randint(1, 101, size=50)

# Calculate the 25th and 75th percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

# Print results
print("Dataset:")
print(data)
print("\n25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Dataset:
[98 99 34 48  8 83 58 46  1 81 67 85 62 34 20 12 78 29 36 79 88 73 98 58
 39 17 49 56 48 11 84 45 97  8 30 16 25 38 43 88 69 27 23 26 65 39 65  9
 85 92]

25th Percentile: 27.5
75th Percentile: 78.75


# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [7]:
# Create two arrays representing two sets of variables
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Compute the correlation coefficient matrix
corr_matrix = np.corrcoef(array1, array2)

# Extract the correlation coefficient between the two arrays
corr_coefficient = corr_matrix[0, 1]

# Print results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nCorrelation Coefficient Matrix:")
print(corr_matrix)
print("\nCorrelation Coefficient between Array 1 and Array 2:")
print(corr_coefficient)

Array 1:
[1 2 3 4 5]

Array 2:
[5 4 3 2 1]

Correlation Coefficient Matrix:
[[ 1. -1.]
 [-1.  1.]]

Correlation Coefficient between Array 1 and Array 2:
-0.9999999999999999


# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [8]:
# Create two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

# Print results
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nMatrix Multiplication Result:")
print(result)

Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Matrix Multiplication Result:
[[ 58  64]
 [139 154]]


# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [9]:
# Create an array of 50 integers between 10 and 1000
data = np.random.randint(10, 1001, size=50)

# Calculate the 10th, 50th (median), and 90th percentiles
percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)
percentile_90 = np.percentile(data, 90)

# Calculate the first (25th) and third (75th) quartiles
quartile_1 = np.percentile(data, 25)
quartile_3 = np.percentile(data, 75)

# Print results
print("Array:")
print(data)
print("\n10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", quartile_1)
print("Third Quartile (75th Percentile):", quartile_3)

Array:
[637 731 109 928 306 321 688 890 426 304 769 940 315 426 724 888 122 984
 247 127 358 323 823 377 428 555 218 794 254 280  58 883 921 612  81 540
 276 617 285 951 467 480 486 629 930 678 775 444 255 102]

10th Percentile: 126.5
50th Percentile (Median): 473.5
90th Percentile: 921.7
First Quartile (25th Percentile): 289.75
Third Quartile (75th Percentile): 759.5


# 66. Create a NumPy array of integers and find the index of a specific element.

In [10]:
# Create a NumPy array of integers
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Specify the element to find
element_to_find = 50

# Find the index of the specific element
indices = np.where(array == element_to_find)

# Print results
print("Array:")
print(array)
print("\nElement to find:", element_to_find)
print("Index of the element:", indices[0])

Array:
[ 10  20  30  40  50  60  70  80  90 100]

Element to find: 50
Index of the element: [4]


# 67. Generate a random NumPy array and sort it in ascending order.

In [11]:
# Generate a random NumPy array
array = np.random.randint(1, 101, size=20)  # Example: 20 random integers between 1 and 100

# Sort the array in ascending order
sorted_array = np.sort(array)

# Print results
print("Original Array:")
print(array)
print("\nSorted Array:")
print(sorted_array)

Original Array:
[ 3 20 30 21  4 66 16 55 18 16 14 86 79 39 17 78  4 80 10 75]

Sorted Array:
[ 3  4  4 10 14 16 16 17 18 20 21 30 39 55 66 75 78 79 80 86]


# 68. Filter elements >20  in the given NumPy array.

 arr = np.array([12, 25, 6, 42, 8, 30])

In [12]:
# Create the NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_elements = arr[arr > 20]

# Print results
print("Original Array:")
print(arr)
print("\nFiltered Elements (greater than 20):")
print(filtered_elements)

Original Array:
[12 25  6 42  8 30]

Filtered Elements (greater than 20):
[25 42 30]


# 69. **Filter** elements which are divisible by 3 from a given NumPy array.
 arr = np.array([1, 5, 8, 12, 15])

In [13]:
# Create the NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_elements = arr[arr % 3 == 0]

# Print results
print("Original Array:")
print(arr)
print("\nFiltered Elements (divisible by 3):")
print(filtered_elements)

Original Array:
[ 1  5  8 12 15]

Filtered Elements (divisible by 3):
[12 15]


# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
 arr = np.array([10, 20, 30, 40, 50])

In [14]:
# Create the NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements ≥ 20 and ≤ 40
filtered_elements = arr[(arr >= 20) & (arr <= 40)]

# Print results
print("Original Array:")
print(arr)
print("\nFiltered Elements (≥ 20 and ≤ 40):")
print(filtered_elements)

Original Array:
[10 20 30 40 50]

Filtered Elements (≥ 20 and ≤ 40):
[20 30 40]


# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
 arr = np.array([1, 2, 3])


In [15]:
# Create the NumPy array
arr = np.array([1, 2, 3])

# Check the byte order
byte_order = arr.dtype.byteorder

# Print results
print("Array:")
print(arr)
print("\nByte Order:", byte_order)

Array:
[1 2 3]

Byte Order: =


# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [16]:
# Create the NumPy array with a specific dtype
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original Array:")
print(arr)
print("Byte Order (before swapping):", arr.dtype.byteorder)

# Perform byte swapping in place
arr.byteswap(inplace=True)

# Print the swapped array and its byte order
print("\nArray after Byte Swapping:")
print(arr)
print("Byte Order (after swapping):", arr.dtype.byteorder)

Original Array:
[1 2 3]
Byte Order (before swapping): =

Array after Byte Swapping:
[16777216 33554432 50331648]
Byte Order (after swapping): =


# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [17]:

# Create the NumPy array with a specific dtype
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array
print("Original Array:")
print(arr)
print("Original Array (byte order):", arr.dtype.byteorder)

# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Print the new array with swapped byte order
print("\nArray with Swapped Byte Order:")
print(swapped_arr)
print("Swapped Array (byte order):", swapped_arr.dtype.byteorder)

Original Array:
[1 2 3]
Original Array (byte order): =

Array with Swapped Byte Order:
[16777216 33554432 50331648]
Swapped Array (byte order): >


# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [18]:
import numpy as np
import sys

# Create the NumPy array with a specific dtype
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's endianness
system_endianness = 'little' if sys.byteorder == 'little' else 'big'

# Determine the desired endianness for the new byte order
desired_endianness = 'big' if system_endianness == 'little' else 'little'

# Swap byte order conditionally based on system endianness
if arr.dtype.byteorder != desired_endianness:
    swapped_arr = arr.newbyteorder(desired_endianness)
else:
    swapped_arr = arr.copy()  # No change needed if already in desired endianness

# Print results
print("Original Array:")
print(arr)
print("Original Array (byte order):", arr.dtype.byteorder)

print("\nSwapped Array:")
print(swapped_arr)
print("Swapped Array (byte order):", swapped_arr.dtype.byteorder)

Original Array:
[1 2 3]
Original Array (byte order): =

Swapped Array:
[16777216 33554432 50331648]
Swapped Array (byte order): >


# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [19]:
import sys

# Create the NumPy array with a specific dtype
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's endianness
system_endianness = sys.byteorder

# Check the array's byte order
array_byteorder = arr.dtype.byteorder

# Determine if byte swapping is necessary
if array_byteorder == '=':
    # Native byte order, no swapping needed
    print("Array is in native byte order. No swapping needed.")
elif array_byteorder == system_endianness:
    # Array byte order matches system endianness
    print("Array byte order matches system endianness. No swapping needed.")
else:
    # Array byte order does not match system endianness
    print("Byte swapping needed to match system endianness.")

# Print results for clarity
print("System Endianness:", system_endianness)
print("Array Byte Order:", array_byteorder)

Array is in native byte order. No swapping needed.
System Endianness: little
Array Byte Order: =


# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`

In [20]:
import numpy as np

# Create the original NumPy array with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of the original array
copy_arr = arr1.copy()

# Modify an element in the copied array
copy_arr[0] = 100  # Change the first element to 100

# Print the original and copied arrays
print("Original Array (arr1):")
print(arr1)
print("\nCopied Array (copy_arr) after modification:")
print(copy_arr)

# Check if the modification affected the original array
if np.array_equal(arr1, copy_arr):
    print("\nModification in copy_arr affected arr1.")
else:
    print("\nModification in copy_arr did not affect arr1.")

Original Array (arr1):
[ 1  2  3  4  5  6  7  8  9 10]

Copied Array (copy_arr) after modification:
[100   2   3   4   5   6   7   8   9  10]

Modification in copy_arr did not affect arr1.


# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [21]:
# Create a 2D NumPy array of shape (3, 3) with random integers
matrix = np.random.randint(1, 100, size=(3, 3))

# Print the original matrix
print("Original Matrix:")
print(matrix)

# Extract a slice from the matrix
# For example, taking the sub-array of the first two rows and columns
view_slice = matrix[:2, :2]

# Print the extracted slice
print("\nExtracted Slice:")
print(view_slice)

# Modify an element in the slice
view_slice[0, 0] = 999

# Print the modified slice
print("\nModified Slice:")
print(view_slice)

# Print the original matrix after modifying the slice
print("\nOriginal Matrix after modifying the slice:")
print(matrix)

Original Matrix:
[[64  5 65]
 [94 15 24]
 [14 80 56]]

Extracted Slice:
[[64  5]
 [94 15]]

Modified Slice:
[[999   5]
 [ 94  15]]

Original Matrix after modifying the slice:
[[999   5  65]
 [ 94  15  24]
 [ 14  80  56]]


# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`

In [22]:
# Create a NumPy array of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Print the original array
print("Original Array (array_a):")
print(array_a)

# Extract a slice from the array
# For example, taking a sub-array of the first three rows and columns
view_b = array_a[:3, :2]

# Print the extracted slice
print("\nExtracted Slice (view_b):")
print(view_b)

# Broadcast addition of 5 to the slice
view_b += 5

# Print the modified slice
print("\nModified Slice (view_b):")
print(view_b)

# Print the original array after modifying the slice
print("\nOriginal Array after modifying the slice:")
print(array_a)

Original Array (array_a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Extracted Slice (view_b):
[[1 2]
 [4 5]
 [7 8]]

Modified Slice (view_b):
[[ 6  7]
 [ 9 10]
 [12 13]]

Original Array after modifying the slice:
[[ 6  7  3]
 [ 9 10  6]
 [12 13  9]
 [10 11 12]]


# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [23]:
# Create a NumPy array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Print the original array
print("Original Array (orig_array):")
print(orig_array)

# Create a reshaped view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)

# Print the reshaped view
print("\nReshaped View (reshaped_view):")
print(reshaped_view)

# Modify an element in the reshaped view
reshaped_view[0, 0] = 99

# Print the modified view
print("\nModified View (reshaped_view):")
print(reshaped_view)

# Print the original array after modifying the view
print("\nOriginal Array after modifying the view:")
print(orig_array)

Original Array (orig_array):
[[1 2 3 4]
 [5 6 7 8]]

Reshaped View (reshaped_view):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified View (reshaped_view):
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]

Original Array after modifying the view:
[[99  2  3  4]
 [ 5  6  7  8]]


# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`

In [24]:
# Create a NumPy array of shape (3, 4) with random integers
data = np.random.randint(1, 20, size=(3, 4))

# Print the original array
print("Original Array (data):")
print(data)

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Print the extracted copy
print("\nExtracted Copy (data_copy):")
print(data_copy)

# Modify an element in the copied array
if data_copy.size > 0:  # Ensure there is at least one element to modify
    data_copy[0] = 99  # Change the first element to 99

# Print the modified copy
print("\nModified Copy (data_copy):")
print(data_copy)

# Print the original array after modifying the copy
print("\nOriginal Array after modifying the copy:")
print(data)

Original Array (data):
[[ 2 17 19  3]
 [ 7  4 17  8]
 [ 6  8  9  4]]

Extracted Copy (data_copy):
[17 19  7 17  8  6  8  9]

Modified Copy (data_copy):
[99 19  7 17  8  6  8  9]

Original Array after modifying the copy:
[[ 2 17 19  3]
 [ 7  4 17  8]
 [ 6  8  9  4]]


# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them

In [25]:
# Create two matrices A and B of identical shape with integer values
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[6, 5, 4], [3, 2, 1]])

# Print matrices
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Perform addition
addition_result = A + B

# Perform subtraction
subtraction_result = A - B

# Print results
print("\nAddition of A and B:")
print(addition_result)

print("\nSubtraction of B from A:")
print(subtraction_result)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[6 5 4]
 [3 2 1]]

Addition of A and B:
[[7 7 7]
 [7 7 7]]

Subtraction of B from A:
[[-5 -3 -1]
 [ 1  3  5]]


# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [26]:
# Generate two matrices C (3x2) and D (2x4)
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

# Print the matrices
print("Matrix C:")
print(C)

print("\nMatrix D:")
print(D)

# Perform matrix multiplication
result = np.dot(C, D)
# Alternatively, you can use the @ operator
# result = C @ D

# Print the result
print("\nMatrix multiplication result (C @ D):")
print(result)

Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

Matrix multiplication result (C @ D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


# 83. Create a matrix `E` and find its transpose.

In [27]:
# Create a matrix E (for example, 3x2 matrix)
E = np.array([[1, 2], [3, 4], [5, 6]])

# Print the original matrix
print("Matrix E:")
print(E)

# Find the transpose of the matrix E
E_transpose = E.T
# Alternatively, you can use np.transpose(E)
# E_transpose = np.transpose(E)

# Print the transposed matrix
print("\nTranspose of Matrix E:")
print(E_transpose)

Matrix E:
[[1 2]
 [3 4]
 [5 6]]

Transpose of Matrix E:
[[1 3 5]
 [2 4 6]]


# 84. Generate a square matrix `F` and compute its determinant

In [28]:
# Generate a square matrix F (for example, a 3x3 matrix)
F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Print the original matrix
print("Matrix F:")
print(F)

# Compute the determinant of matrix F
det_F = np.linalg.det(F)

# Print the determinant
print("\nDeterminant of Matrix F:")
print(det_F)

Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of Matrix F:
0.0


# 85. Create a square matrix `G` and find its inverse.

In [29]:
# Generate a square matrix G (for example, a 3x3 matrix)
G = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Print the original matrix
print("Matrix G:")
print(G)

# Compute the inverse of matrix G
try:
    G_inverse = np.linalg.inv(G)
    # Print the inverse
    print("\nInverse of Matrix G:")
    print(G_inverse)
except np.linalg.LinAlgError:
    print("\nMatrix G is singular and cannot be inverted.")

Matrix G:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Inverse of Matrix G:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
